# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  host: localhost
  port: 3306
  database: autocomplete
  username: root
  password: 

production:
  adapter: mysql2
  host: db
  port: 3306
  username: user
  password: user
  database: default

# production:
#    adapter: postgresql
#    database: db/production.sqlite3
